name: Convert Illustrator to PDF

on:
  push:
    paths:
      - "**.ai"  # Kích hoạt khi có file .ai được push lên repo

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cài đặt Inkscape
        run: sudo apt-get install inkscape

      - name: Chuyển đổi .ai sang PDF
        run: |
          for file in *.ai; do
            inkscape "$file" --export-filename="${file%.ai}.pdf"
          done

      - name: Upload file PDF
        uses: actions/upload-artifact@v3
        with:
          name: converted-pdf
          path: "*.pdf"
